/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.apache.commons.math3.complex.Complex;
import org.testng.annotations.*;
import static org.testng.Assert.*;

public class LibraryTest {
    @Test
    public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test
    public void someMathLibraryMethodReturnsComplex() {
        Library classUnderTest = new Library();
        assertEquals(classUnderTest.someMathLibraryMethod(), Complex.valueOf(3, 5),"someLibraryMethod should return complex");
    }
}
