import org.apache.commons.math3.complex.Complex;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public Complex someMathLibraryMethod() {
        return Complex.valueOf(3, 5);
    }
}
